### ISSUE TITLE
Change split with prepend and postpend back ticks. 

### ISSUE THREAD

**Issue by aldldl** [tovernaar123/Exp-discord-bot#32]
```suggestion
                msg.channel.send(`${name}:\n\`\`\`json\n${JSON.stringify(finaldata, null, 2)}\`\`\``, { split: true });
```
This should work to split it automatically. Though I will need to test it and then append the ```

_Originally posted by @aldldl in https://github.com/tovernaar123/Exp-discord-bot/pull/30#r610002142_

**Comment by aldldl** [comment]
didn't I finish this? not sure actually

**Comment by tovernaar123** [comment]
this will not work since if the charter is too big the code block will be broken up one message will start with 3 backticks
but not end with them, and the second message will only end with backticks. Hope this answers your question
