### ISSUE TITLE
Filter Chat in log

### ISSUE THREAD

**Issue by PHIDIAS0303** [tovernaar123/Exp-discord-bot#8]
Add a option to filter out chat or join / leave event.

**Comment by aldldl** [comment]
Do you want it so you only get join and leave? Or do you want it so you don't see join and leave?

**Comment by PHIDIAS0303** [comment]
Well, only chat or only join leave that kind

**Comment by PHIDIAS0303** [comment]
Just options that you can see 'normal', 'join / leave' only, or say 'join leave and kill' event.

**Comment by tovernaar123** [comment]
done by #17
